# Generated by Django 5.2.9 on 2026-01-29 15:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0018_alter_source_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.articlecategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_duration', models.DurationField(default=datetime.timedelta(days=7))),
                ('categories', models.ManyToManyField(blank=True, through='users.UserCategory', to='feeds.articlecategorymodel')),
                ('favorite_articles', models.ManyToManyField(blank=True, to='feeds.articlemodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usercategory',
            name='usersettings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersettings'),
        ),
        migrations.CreateModel(
            name='UserSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('params', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='feeds.articlecategorymodel')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.source')),
                ('usersettings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersettings')),
            ],
            options={
                'unique_together': {('usersettings', 'source', 'category')},
            },
        ),
        migrations.AddField(
            model_name='usersettings',
            name='sources',
            field=models.ManyToManyField(blank=True, through='users.UserSource', to='feeds.source'),
        ),
        migrations.AlterUniqueTogether(
            name='usercategory',
            unique_together={('usersettings', 'category')},
        ),
    ]
