# Generated by Django 5.2.9 on 2026-03-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersource',
            name='params',
        ),
    ]
