# Generated by Django 5.2.9 on 2026-01-23 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='source',
            new_name='sources',
        ),
    ]
