# Generated by Django 5.2.9 on 2026-01-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_alter_source_url'),
        ('users', '0002_rename_source_usersettings_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='categories',
            field=models.ManyToManyField(blank=True, to='feeds.articlecategorymodel'),
        ),
    ]
