# Generated by Django 5.2.9 on 2026-01-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_alter_source_url'),
        ('users', '0004_alter_usersettings_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='user_settings', to='feeds.source'),
        ),
    ]
