# Generated by Django 5.2.9 on 2026-01-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_alter_articlemodel_source'),
        ('users', '0005_alter_usersettings_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, related_name='user_settings', to='feeds.articlemodel'),
        ),
    ]
