# Generated by Django 5.2.9 on 2026-01-26 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_remove_source_active_remove_source_category_and_more'),
        ('users', '0006_usersettings_favorite_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='sources',
        ),
        migrations.CreateModel(
            name='UserSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('params', models.JSONField(default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='feeds.articlecategorymodel')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.source')),
                ('usersettings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersettings')),
            ],
            options={
                'unique_together': {('usersettings', 'source')},
            },
        ),
    ]
