# Generated by Django 5.2.9 on 2026-01-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_remove_source_active_remove_source_category_and_more'),
        ('users', '0007_remove_usersettings_sources_usersource'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='user_settings', through='users.UserSource', to='feeds.source'),
        ),
    ]
