# Generated by Django 5.2.9 on 2026-01-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_remove_source_active_remove_source_category_and_more'),
        ('users', '0008_usersettings_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='categories',
            field=models.ManyToManyField(blank=True, to='feeds.articlecategorymodel'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, to='feeds.articlemodel'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='sources',
            field=models.ManyToManyField(blank=True, through='users.UserSource', to='feeds.source'),
        ),
        migrations.AlterField(
            model_name='usersource',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
