# Generated by Django 5.2.9 on 2026-01-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usersettings_categories_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersource',
            unique_together=set(),
        ),
    ]
