# Generated by Django 5.2.9 on 2026-01-27 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_remove_source_active_remove_source_category_and_more'),
        ('users', '0010_alter_usersource_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersource',
            unique_together={('usersettings', 'source', 'category')},
        ),
    ]
