# Generated by Django 5.2.9 on 2026-01-27 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0018_alter_source_unique_together'),
        ('users', '0011_alter_usersource_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.articlecategorymodel')),
                ('usersettings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersettings')),
            ],
            options={
                'unique_together': {('usersettings', 'category')},
            },
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='categories',
            field=models.ManyToManyField(blank=True, through='users.UserCategory', to='feeds.articlecategorymodel'),
        ),
    ]
