# Generated by Django 5.2.9 on 2026-01-27 12:32

from django.db import migrations


def migrate_category_data(apps, schema_editor):
    UserSettings = apps.get_model('users', 'UserSettings')
    UserCategory = apps.get_model('users', 'UserCategory')
    
    for usersettings in UserSettings.objects.all():
        for category in usersettings.categories.all():
            UserCategory.objects.get_or_create(
                usersettings=usersettings,
                category=category
            )


def reverse_migrate(apps, schema_editor):
    UserCategory = apps.get_model('users', 'UserCategory')
    UserCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_usercategory_alter_usersettings_categories'),
    ]

    operations = [
        migrations.RunPython(migrate_category_data, reverse_migrate),
    ]