# Generated by Django 5.2.9 on 2026-01-27 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_migrate_category_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='article_duration',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
