# Generated by Django 6.0 on 2025-12-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True)),
                ('link', models.CharField()),
                ('published', models.TimeField()),
                ('summary', models.CharField()),
                ('image_url', models.CharField()),
            ],
        ),
    ]
