# Generated by Django 6.0 on 2025-12-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='image_url',
            field=models.URLField(),
        ),
    ]
