# Generated by Django 6.0 on 2025-12-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_alter_articlemodel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='published',
            field=models.CharField(),
        ),
    ]
