# Generated by Django 6.0 on 2025-12-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_alter_articlemodel_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='published',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
