# Generated by Django 6.0 on 2025-12-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_alter_articlemodel_link_alter_articlemodel_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='published',
            field=models.DateTimeField(),
        ),
    ]
