# Generated by Django 5.2.9 on 2025-12-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_alter_articlemodel_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
