# Generated by Django 5.2.9 on 2025-12-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_alter_articlemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
