# Generated by Django 5.2.9 on 2025-12-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_alter_articlemodel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='category',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
