# Generated by Django 5.2.9 on 2025-12-27 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_articlemodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feeds.articlecategorymodel'),
            preserve_default=False,
        ),
    ]
