# Generated by Django 5.2.9 on 2025-12-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_articlecategorymodel_alter_articlemodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='link',
            field=models.URLField(max_length=350, unique=True),
        ),
    ]
