# Generated by Django 5.2.9 on 2026-01-11 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_alter_articlemodel_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('params', models.JSONField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.articlecategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.articlecategorymodel')),
            ],
        ),
    ]
