# Generated by Django 5.2.9 on 2026-01-22 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_apifeed_rssfeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssfeed',
            name='category',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='category',
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('params', models.JSONField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('RSS', 'RSS'), ('API', 'API')], max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.articlecategorymodel')),
            ],
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='feeds.source'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='APIFeed',
        ),
        migrations.DeleteModel(
            name='RSSFeed',
        ),
    ]
