# Generated by Django 5.2.9 on 2026-01-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_remove_rssfeed_category_remove_articlemodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
