# Generated by Django 5.2.9 on 2026-01-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0014_alter_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
