# Generated by Django 5.2.9 on 2026-01-25 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_alter_source_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='feeds.source'),
        ),
    ]
