# Generated by Django 5.2.9 on 2026-01-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_alter_articlemodel_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='active',
        ),
        migrations.RemoveField(
            model_name='source',
            name='category',
        ),
        migrations.RemoveField(
            model_name='source',
            name='params',
        ),
    ]
