# Generated by Django 5.2.9 on 2026-01-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_remove_source_active_remove_source_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('url', 'source_type')},
        ),
    ]
