# Generated by Django 5.2.9 on 2026-03-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0018_alter_source_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.RemoveField(
            model_name='source',
            name='source_type',
        ),
    ]
